
 let shopItemData=[
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    Price:45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Shirt",
    Price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    Price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    Price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    Price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual Shoes",
    Price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Black Suit",
    Price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Polo Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Denim shirt",
    Price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Denim Pants",
    Price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Normal P-Cap",
    Price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Leather Boots",
    Price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "src/images/img-12.png",
  },
];
